version: '3.7'
services:
  mysql-db:
    image: mysql:5.7
    restart: on-failure
    environment:
      MYSQL_DATABASE: 'mysql-db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'user'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      - spring-boot-example-mysql-compose-network
  spring-boot-example-mysql:
   build: 
      context: .
      dockerfile: Dockerfile
   image: breymer/spring-boot-example-mysql:0.0.2.RELEASE
   ports:
      - "9193:9193"
   restart: always
   links:
      - mysql-db 
   depends_on:
      - mysql-db
   environment:
       SPRING_PROFILES_ACTIVE: docker    
       DATABASE_HOST: mysql-db
       DATABASE_USER: user
       DATABASE_PASSWORD: user
       DATABASE_NAME: mysql-db
       DATABASE_PORT: 3306
   networks:
      - spring-boot-example-mysql-compose-network
# Names our volume
volumes:
  mysql-db:

# Networks to be created to facilitate communication between containers
networks:
  spring-boot-example-mysql-compose-network: